-----------------Please change the Temp table names if required.

DROP TABLE TMP_SRI_MC_BILL_REMINDER;

CREATE TABLE TMP_SRI_MC_BILL_REMINDER PARALLEL(DEGREE 5) AS
SELECT C.ACCOUNT_NO,
C.BILL_FNAME||' '||C.BILL_LNAME CUSTOMER_NAME,
BI.BILL_REF_NO INVOICE_NUMBER,
BI.STATEMENT_DATE,
(NVL((SELECT SUM(CB1.BALANCE_DUE/100) FROM CMF_BALANCE CB1 WHERE CB1.ACCOUNT_NO = BI.ACCOUNT_NO GROUP BY CB1.ACCOUNT_NO),0)) TOTAL_DUE_AMOUNT,
(NVL((SELECT CB2.BALANCE_DUE/100 FROM CMF_BALANCE CB2 WHERE CB2.BILL_REF_NO = BI.BILL_REF_NO),0)) CURRENT_DUE_AMOUNT,
BI.PAYMENT_DUE_DATE CURRENT_DUE_DATE,
(NVL((SELECT SUM(CB3.BALANCE_DUE/100) FROM CMF_BALANCE CB3 WHERE CB3.ACCOUNT_NO = BI.ACCOUNT_NO 
     AND CB3.BILL_REF_NO <> BI.BILL_REF_NO AND CB3.BILL_REF_NO <> 0  GROUP BY CB3.ACCOUNT_NO),0)) PAST_DUE_AMOUNT,
(NVL((SELECT BI2.PAYMENT_DUE_DATE FROM BILL_INVOICE BI2 WHERE BI2.ACCOUNT_NO = BI.ACCOUNT_NO 
AND BI2.STATEMENT_DATE = TRUNC(TO_DATE(add_months(SYSDATE, -1)),'MM') 
AND BI2.PREP_STATUS <> 4 AND BI2.PREP_ERROR_CODE IS NULL AND BI2.BACKOUT_STATUS = 0 
AND BI2.BILL_SEQUENCE_NUM > 0 AND BI2.TO_DATE = BI.STATEMENT_DATE),'1-JAN-1990')) PAST_DUE_DATE,
C.ACCOUNT_STATUS,C.COLLECTION_INDICATOR
FROM CMF C, BILL_INVOICE BI
WHERE C.ACCOUNT_TYPE = 1
AND C.ACCOUNT_CATEGORY = 10
AND C.ACCOUNT_NO = BI.ACCOUNT_NO
AND BI.STATEMENT_DATE = TRUNC(TO_DATE(add_months(SYSDATE, 0)),'MM')
AND BI.PREP_STATUS <> 4
AND BI.PREP_ERROR_CODE IS NULL
AND BI.BACKOUT_STATUS = 0
AND BI.BILL_SEQUENCE_NUM > 0;

DROP TABLE TMP_SRI_MC_BILL_REMINDER_1;

CREATE TABLE TMP_SRI_MC_BILL_REMINDER_1 AS
SELECT SV.PARENT_ACCOUNT_NO,
         CASE
           WHEN SCV.SERVICE_CATEGORY_ID IN ( 8, 18 ) THEN 'Landline'
           WHEN SCV.SERVICE_CATEGORY_ID = 24 THEN 'GTT Fibre'
		   WHEN SCV.SERVICE_CATEGORY_ID = 4 THEN 'Mobile'
           ELSE SCV.DISPLAY_VALUE
         END AS SERVICE_TYPE,
         COUNT(*) AS SUB_COUNT,
     0 AS IS_CSA
  FROM   SUBSCRIBER_VIEW SV,
         OFFER_REF OFR,
         SERVICE_CATEGORY_VALUES SCV
  WHERE  PARENT_ACCOUNT_NO IN (SELECT ACCOUNT_NO
                               FROM   TMP_SRI_MC_BILL_REMINDER)
         AND SV.PRIMARY_OFFER_ID = OFR.OFFER_ID
         AND SV.VIEW_STATUS = 2
         AND OFR.RESELLER_VERSION_ID = (SELECT MAX(RESELLER_VERSION_ID)
                                        FROM   RESELLER_VERSION)
         AND OFR.SERVICE_CATEGORY_ID = SCV.SERVICE_CATEGORY_ID
         AND SCV.SERVICE_VERSION_ID = (SELECT MAX(SERVICE_VERSION_ID)
                                       FROM   SERVICE_VERSION)
  GROUP  BY SV.PARENT_ACCOUNT_NO,
            CASE
              WHEN SCV.SERVICE_CATEGORY_ID IN ( 8, 18 ) THEN 'Landline'
              WHEN SCV.SERVICE_CATEGORY_ID = 24 THEN 'GTT Fibre'
			  WHEN SCV.SERVICE_CATEGORY_ID = 4 THEN 'Mobile'
              ELSE SCV.DISPLAY_VALUE
            END;

UPDATE TMP_SRI_MC_BILL_REMINDER_1
SET    IS_CSA = 1
WHERE  PARENT_ACCOUNT_NO IN (SELECT PARENT_ACCOUNT_NO
                             FROM   TMP_SRI_MC_BILL_REMINDER_1
                             GROUP  BY PARENT_ACCOUNT_NO
                             HAVING COUNT(*) > 1);
                             
COMMIT;

DROP TABLE TMP_SRI_MC_BILL_REMINDER_FIN;

CREATE TABLE  TMP_SRI_MC_BILL_REMINDER_FIN AS
SELECT DISTINCT TMP.*,
                 CASE
                   WHEN TMP1.IS_CSA = 1 THEN 'Multi Service'
                   ELSE TMP1.SERVICE_TYPE
                 END AS SERVICE_TYPE
 FROM   TMP_SRI_MC_BILL_REMINDER TMP,
        TMP_SRI_MC_BILL_REMINDER_1 TMP1
 WHERE  TMP.ACCOUNT_NO = TMP1.PARENT_ACCOUNT_NO (+);

UPDATE TMP_SRI_MC_BILL_REMINDER_FIN SET PAST_DUE_DATE = NULL WHERE PAST_DUE_DATE = '1-JAN-1990';

COMMIT;

DROP TABLE TMP_SRI_MC_BILL_REMINDER_FIN_1;

CREATE TABLE TMP_SRI_MC_BILL_REMINDER_FIN_1 AS
SELECT DISTINCT ACCOUNT_NO,SERVICE_TYPE,CUSTOMER_NAME, INVOICE_NUMBER, STATEMENT_DATE, TOTAL_DUE_AMOUNT, CURRENT_DUE_AMOUNT, 
CURRENT_DUE_DATE, PAST_DUE_AMOUNT, PAST_DUE_DATE
FROM TMP_SRI_MC_BILL_REMINDER_FIN  
WHERE ((PAST_DUE_AMOUNT > 100 AND EXTRACT(MONTH FROM PAST_DUE_DATE) <= EXTRACT(MONTH FROM SYSDATE) 
AND EXTRACT(YEAR FROM PAST_DUE_DATE) <= EXTRACT(YEAR FROM SYSDATE))
OR (CURRENT_DUE_AMOUNT > 100 AND EXTRACT(MONTH FROM CURRENT_DUE_DATE) <= EXTRACT(MONTH FROM SYSDATE)
AND EXTRACT(YEAR FROM CURRENT_DUE_DATE) <= EXTRACT(YEAR FROM SYSDATE)))
AND ACCOUNT_STATUS IN (-1,0)
AND COLLECTION_INDICATOR = 0
AND SERVICE_TYPE IS NOT NULL;

SELECT * FROM TMP_SRI_MC_BILL_REMINDER_FIN_1;