
--APPLICATIONS FOR QUARTER
SELECT
COUNT(1)
FROM(
SELECT
DISTINCT ACCOUNT_NO,SUBSCR_NO
FROM
GTT_REPORTING.PUC_LAND_INSTALL_AP
WHERE
DATE(APPLICATION_DATE) BETWEEN '2021-05-01' and '2021-07-31'
) AS T

---APPLICATION RECEIVED AND INSTALLED IN THIS QUARTER
SELECT
COUNT(1)
FROM(
SELECT
DISTINCT ACCOUNT_NO, SUBSCR_NO
FROM
GTT_REPORTING.PUC_INSTALL_EXCHANGE
WHERE
DATE(APPLICATION_DATE) BETWEEN '2021-05-01' and '2021-07-31'
AND DATE(INSTALLATION_DATE) BETWEEN '2021-05-01' and '2021-07-31'
) AS T

---INSTALLATION FOR APPLICATIONS FROM PREVIOUS QUARTERS

SELECT
COUNT(1)
FROM(
SELECT
DISTINCT ACCOUNT_NO, SUBSCR_NO
FROM
GTT_REPORTING.PUC_INSTALL_EXCHANGE
WHERE
DATE(APPLICATION_DATE) NOT BETWEEN '2021-05-01' and '2021-07-31'
AND DATE(INSTALLATION_DATE) BETWEEN '2021-05-01' and '2021-07-31'
) AS T

----PREVIOUS QUARTERS INSTALLATION BY GEOGRAPHIC LOCATION 
SELECT
INSTALL_MONTH, LOCATION,COUNT(1)
FROM(
SELECT
DISTINCT 
A.ACCOUNT_NO, 
B.SUBSCR_NO,
A.APPLICATION_DATE AS APPLICATION_DATE, 
--SUBSTRING(B.EXTERNAL_ID,1,4) AS EXCHANGE,
CASE
 WHEN SUBSTRING(B.EXTERNAL_ID,1,4) IN('SRVT','SOPH','GTCO','LIND','NACO','CRSC') THEN 'URBAN'
 ELSE
     'SUBURBAN/RURAL'
END AS LOCATION,
TO_CHAR(A.INSTALLATION_DATE,'YYYY-MM') AS INSTALL_MONTH
FROM
GTT_REPORTING.PUC_INSTALL_EXCHANGE A
LEFT JOIN(
SELECT 
ACCOUNT_NO, SUBSCR_NO, EXTERNAL_ID,MAX(INSTALLATION_DATE) AS INSTALLATION_DATE,MAX(RECORD_DATE)  AS RECORD_DATE
FROM
GTT_REPORTING.PUC_INSTALL_EXCHANGE
WHERE
DATE(INSTALLATION_DATE)  BETWEEN '2021-05-01' and '2021-07-31'
GROUP BY ACCOUNT_NO, SUBSCR_NO, EXTERNAL_ID
)AS C ON A.ACCOUNT_NO=C.ACCOUNT_NO AND A.SUBSCR_NO=C.SUBSCR_NO AND A.EXTERNAL_ID=C.EXTERNAL_ID 
LEFT JOIN
( 
   SELECT
   EXTERNAL_ID,ACCOUNT_NO,SUBSCR_NO
   FROM
   GTT_REPORTING.EXTERNAL_ID_EQUIP_MAP
   WHERE
   EXTERNAL_ID_TYPE=19
   AND (ACCOUNT_NO,SUBSCR_NO,ACTIVE_DATE) IN(
	   SELECT
	   ACCOUNT_NO,SUBSCR_NO,MAX(ACTIVE_DATE) AS ACTIVE_DATE
	   FROM
	   GTT_REPORTING.EXTERNAL_ID_EQUIP_MAP
	   WHERE
	   EXTERNAL_ID_TYPE=19
	   GROUP BY ACCOUNT_NO,SUBSCR_NO
   )

)B ON A.ACCOUNT_NO=B.ACCOUNT_NO AND A.SUBSCR_NO=B.SUBSCR_NO
WHERE
DATE(A.INSTALLATION_DATE) BETWEEN '2021-05-01' and '2021-07-31'
AND DATE(APPLICATION_DATE) NOT BETWEEN '2021-05-01' and '2021-07-31'
AND A.INSTALLATION_DATE=C.INSTALLATION_DATE
AND A.RECORD_DATE=C.RECORD_DATE
) AS T
GROUP BY INSTALL_MONTH, LOCATION





----THIS QUARTER INSTALLATION BY GEOGRAPHIC LOCATION 
SELECT
INSTALL_MONTH, LOCATION,COUNT(1)
FROM(
SELECT
DISTINCT 
A.ACCOUNT_NO, 
B.SUBSCR_NO,
A.APPLICATION_DATE AS APPLICATION_DATE, 
--SUBSTRING(B.EXTERNAL_ID,1,4) AS EXCHANGE,
CASE
 WHEN SUBSTRING(B.EXTERNAL_ID,1,4) IN('SRVT','SOPH','GTCO','LIND','NACO','CRSC') THEN 'URBAN'
 ELSE
     'SUBURBAN/RURAL'
END AS LOCATION,
TO_CHAR(A.INSTALLATION_DATE,'YYYY-MM') AS INSTALL_MONTH
FROM
GTT_REPORTING.PUC_INSTALL_EXCHANGE A
LEFT JOIN(
SELECT 
ACCOUNT_NO, SUBSCR_NO, EXTERNAL_ID,MAX(INSTALLATION_DATE) AS INSTALLATION_DATE,MAX(RECORD_DATE)  AS RECORD_DATE
FROM
GTT_REPORTING.PUC_INSTALL_EXCHANGE
WHERE
DATE(INSTALLATION_DATE)  BETWEEN '2021-05-01' and '2021-07-31'
GROUP BY ACCOUNT_NO, SUBSCR_NO, EXTERNAL_ID
)AS C ON A.ACCOUNT_NO=C.ACCOUNT_NO AND A.SUBSCR_NO=C.SUBSCR_NO AND A.EXTERNAL_ID=C.EXTERNAL_ID 
LEFT JOIN
( 
   SELECT
   EXTERNAL_ID,ACCOUNT_NO,SUBSCR_NO
   FROM
   GTT_REPORTING.EXTERNAL_ID_EQUIP_MAP
   WHERE
   EXTERNAL_ID_TYPE=19
   AND (ACCOUNT_NO,SUBSCR_NO,ACTIVE_DATE) IN(
	   SELECT
	   ACCOUNT_NO,SUBSCR_NO,MAX(ACTIVE_DATE) AS ACTIVE_DATE
	   FROM
	   GTT_REPORTING.EXTERNAL_ID_EQUIP_MAP
	   WHERE
	   EXTERNAL_ID_TYPE=19
	   GROUP BY ACCOUNT_NO,SUBSCR_NO
   )

)B ON A.ACCOUNT_NO=B.ACCOUNT_NO AND A.SUBSCR_NO=B.SUBSCR_NO
WHERE
DATE(A.INSTALLATION_DATE) BETWEEN '2021-05-01' and '2021-07-31'
AND DATE(APPLICATION_DATE)  BETWEEN '2021-05-01' and '2021-07-31'
AND A.INSTALLATION_DATE=C.INSTALLATION_DATE
AND A.RECORD_DATE=C.RECORD_DATE
) AS T
GROUP BY INSTALL_MONTH, LOCATION

SELECT
DATE_TRUNC('MONTH',APPLICATION_DATE::DATE),
DATE_TRUNC('MONTH',INSTALLATION_DATE::DATE),
COUNT(DISTINCT SUBSCR_NO)
FROM 
GTT_REPORTING.PUC_LAND_INSTALL_AP
WHERE
ACCOUNT_NO IN(
SELECT 
ACCOUNTNUMBER
FROM
ATNI_PROD.ATNI_ANALYTICS.SUBSCRIBER_BG_END_WEEKLY_MONTHLY_SNAPSHOT_DAILYACTIVITY
WHERE
DATESTART BETWEEN '2021-05-01' and '2021-07-31'
AND OPERATING_COMPANY_CODE=1
AND TECHNOLOGY_TYPE_CODE=8
AND DATASET_TYPE='DAILY_SUB_ACTIVITY'
AND ACTIVATIONS<>0
) 
GROUP BY 1



SELECT
DATE_TRUNC('MONTH',INSTALLATION_DATE::DATE),
COUNT(DISTINCT SUBSCR_NO)
FROM 
GTT_REPORTING.PUC_INSTALL_EXCHANGE
WHERE
ACCOUNT_NO IN(
SELECT 
ACCOUNTNUMBER
FROM
ATNI_PROD.ATNI_ANALYTICS.SUBSCRIBER_BG_END_WEEKLY_MONTHLY_SNAPSHOT_DAILYACTIVITY
WHERE
DATESTART BETWEEN '2021-05-01' and '2021-07-31'
AND OPERATING_COMPANY_CODE=1
AND TECHNOLOGY_TYPE_CODE=8
AND DATASET_TYPE='DAILY_SUB_ACTIVITY'
AND ACTIVATIONS<>0
) 
GROUP BY 1


955

SELECT
APPLICATION_DATE,
COUNT(1)
FROM(
SELECT
*
FROM
GTT_REPORTING.PUC_LAND_INSTALL_AP
WHERE
DATE(APPLICATION_DATE) BETWEEN '2021-05-01' and '2021-07-31'
) AS T
GROUP 










SELECT
DATE(INSTALLATION_DATE),
COUNT(1)
FROM
GTT_REPORTING.PUC_INSTALL_EXCHANGE
WHERE
--DATE(APPLICATION_DATE) NOT BETWEEN '2021-05-01' and '2021-07-31'
DATE(INSTALLATION_DATE) BETWEEN '2021-05-01' and '2021-07-31'
GROUP BY 1
